using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AccessHomes.Domain.Enum
{
    public enum Cities
    {
        Aba,
        Abakaliki,
        Abeokuta,
        Abonnema,
        Abuja,
        [Display(Name = "Ado Ekiti")]
        AdoEkiti,
        Afikpo,
        Agbor,
        Agulu,
        Aku,
        Akure,
        Amaigbo,
        Ankpa,
        Asaba,
        Auchi,
        Awka,
        Azare,
        Bama,
        Bauchi,
        Bende,
        [Display(Name = "Benin City")]
        BeninCity,
        Bida,
        [Display(Name = "Birnin Kebb")]
        BirninKebbi,
        Biu,
        Buguma,
        Calabar,
        Damaturu,
        Daura,
        Dutse,
        Ede,
        Effium,
        [Display(Name = "Effon Alaiye")]
        EffonAlaiye,
        [Display(Name = "Eha Amufu")]
        EhaAmufu,
        Ejigbo,
        Ekpoma,
        Enugu,
        [Display(Name = "Enugu Ukwu")]
        EnuguUkwu,
        Epe,
        Etiti,
        [Display(Name = "Ezza Inyimagu")]
        EzzaInyimagu,
        Funtua,
        Gamboru,
        Gashua,
        Gboko,
        Gbongan,
        Gombe,
        Gusau,
        Hadejia,
        Ibadan,
        Idah,
        Ife,
        Ifo,
        Ifon,
        Igboho,
        [Display(Name = "Igbo Ora")]
        IgboOra,
        [Display(Name = "Igbo Ukwu")]
        IgboUkwu,
        Ihiala,
        [Display(Name = "Ijebu Igbo")]
        IjebuIgbo,
        [Display(Name = "Ijebu Ode")]
        IjebuOde,
        Ijero,
        Ikare,
        Ikeja,
        Ikerre,
        Ikire,
        Ikirun,
        Ikom,
        Ikorodu,
        [Display(Name = "Ikot Ekpene")]
        IkotEkpene,
        [Display(Name = "Ila Orangun")]
        IlaOrangun,
        [Display(Name = "Ilawe Ekiti")]
        IlaweEkiti,
        Ilesha,
        Ilobu,
        Ilorin,
        Inisa,
        Ise,
        Iseyin,
        Ishieke,
        Iwo,
        Jalingo,
        Jimeta,
        Jos,
        Kaduna,
        Kafanchan,
        Kagoro,
        Kano,
        Katsina,
        [Display(Name = "Kaura Namoda")]
        KauraNamoda,
        Keffi,
        Kishi,
        Kontagora,
        Kuroko,
        Lafia,
        Lagos,
        Lokoja,
        Maiduguri,
        Makurdi,
        Malumfashi,
        Minna,
        Modakeke,
        Mubi,
        Nguru,
        Nkpor,
        Nnewi,
        Nsukka,
        Numan,
        Obosi,
        Offa,
        Ogaminan,
        Ogbomosho,
        Ohafia,
        [Display(Name = "Oka Akoko")]
        OkaAkoko,
        Okene,
        Okigwi,
        Okitipupa,
        Okpogho,
        Okrika,
        Ondo,
        Onitsha,
        Oron,
        Oshogbo,
        Otukpo,
        Owerri,
        Owo,
        Oyo,
        Ozubulu,
        [Display(Name = "Port Harcourt")]
        PortHarcourt,
        Sagamu,
        [Display(Name = "Sango Otta")]
        SangoOtta,
        Sapele,
        Shaki,
        Sokoto,
        Suleja,
        Uga,
        Ugep,
        Ughelli,
        Umuahia,
        Uromi,
        Uyo,
        Warri,
        Wukari,
        Yenagoa,
        Yola,
        Zaria
    }
}
